name: dartshine
description: A web framework which aims to have a clear, clean syntax.
version: 1.0.2
repository: https://github.com/VeroniDeev/dartshine
homepage: https://github.com/VeroniDeev/dartshine
issue_tracker: https://github.com/VeroniDeev/dartshine/issues
documentation: https://github.com/VeroniDeev/dartshine/wiki

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  mime: ^1.0.5
  sqlite3: ^2.4.3
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  dartshine: dartshine


platforms:
  windows:
  macos:
  linux:
